name: Docker Build and Publish

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  IMAGE_NAME: xixka/filebot-zh

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get China time timestamp
        id: china_time
        run: |
          china_time=$(TZ="Asia/Shanghai" date +'%Y%m%d-%H%M')
          echo "VERSION_TAG=$china_time" >> $GITHUB_OUTPUT
        shell: bash

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: |
            image=moby/buildkit:master

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64, linux/arm64
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ steps.china_time.outputs.VERSION_TAG }} 
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Show published image info
        run: |
          echo "pull Docker Hub:"
          echo "- ${{ env.IMAGE_NAME }}:latest"
          echo "- ${{ env.IMAGE_NAME }}:${{ steps.china_time.outputs.VERSION_TAG }}"
